Git and Docker
trilogy-group/tu2k22-rehanullah-trial pull request #4
Opened 2022-08-02 18:58 UTC by rehan-ti

Completed the assignment

2022-08-02 19:00 UTC, kushal-ti commented
resolve all the merge conflicts first please

2022-08-02 19:11 UTC, rehan-ti commented
Yeah sorry. Resolved them now.

2022-08-02 19:21 UTC, kushal-ti requested changes
one comment for you to resolve, rest looks good

2022-08-02 19:21 UTC, kushal-ti commented on README.md
> +git add
you're supposed to list the specific commands you used and their order

2022-08-02 19:21 UTC, kushal-ti commented on README.md
> +git add
for the git part atleast

2022-08-02 19:21 UTC, kushal-ti commented on internal_server.py
> +class Sum(BaseModel):
types always a plus, good job

2022-08-02 19:21 UTC, kushal-ti commented on .github/workflows/validate_dockerfile.yml
> +name: Validate Docker File
you pushed everything all at once in in a single commit. Avoid this in the future. commits should be small for several reason, eg. so that rolling back on a faulty one can be done with ease without taking other functionality that was also pushed in the same commit

2022-08-02 19:21 UTC, kushal-ti commented
please make the necessary change

2022-08-02 20:00 UTC, rehan-ti commented on internal_server.py
> +class Sum(BaseModel):
Thank you.

2022-08-02 20:02 UTC, rehan-ti commented on .github/workflows/validate_dockerfile.yml
> +name: Validate Docker File
Got it. I will remember that for sure. Locally I did all the commits and now I realize that I should have been pushing them along as well.

2022-08-02 20:03 UTC, rehan-ti commented on README.md
> +git add
Okay I will update the Readme.

2022-08-03 10:22 UTC, kushal-ti approved these changes
sorry it took so long :joy:

2022-08-03 10:40 UTC, merged